server:
  port: 8080  # Cấu hình cổng cho máy chủ web, máy chủ sẽ chạy tại http://localhost:8080
  servlet:
    context-path: /identity  # Định nghĩa context path (đường dẫn gốc) cho ứng dụng, khi truy cập sẽ phải thêm "/identity" vào URL.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service  # Database URL
    username: root  # Database username
    password: root  # Database password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signedKey: vR7scslv0TiKGvqKsNovOdVa4CZVdYJFzjCuTIdsXuO9PSw1Pvj6OnGbCCClQLwn
